name: apps
version: 1

plugins:
    - '@yarnpkg/plugin-workspace-tools'

workspaces:
    packages:
        - packages/*

# If you want to specify custom commands or scripts, you can include them here
scripts:
    build: yarn workspaces foreach run build
    test: yarn workspaces foreach run test
