name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/html
            if [ ! -d ".git" ]; then
              git init
              git remote add origin ${{ secrets.GIT_REPO_URL }}
            else
              git remote set-url origin ${{ secrets.GIT_REPO_URL }}
            fi
            git fetch origin
            git reset --hard origin/main
            yarn install
            yarn build
            if [ -f /var/www/html/ecosystem.config.js ]; then
              if pm2 list | grep -q 'chat-app'; then
                pm2 restart /var/www/html/ecosystem.config.js --env production
              else
                pm2 start /var/www/html/ecosystem.config.js --env production
              fi
            else
              echo "ecosystem.config.js not found!"
              exit 1
            fi
            rm -rf node_modules yarn.lock
            sudo service nginx reload
